#%RAML 1.0 Library
types:
  insertStudent: !include ../dataTypes/insertStudentDataType.raml
  updateStudent: !include ../dataTypes/updateStudentDataType.raml
traits:
  headers: !include ../exchange_modules/53e3ee78-d9e6-4719-8cb5-e06be3579d4b/commoncode/1.0.0/commoncode.raml
  errorCodes: !include ../exchange_modules/53e3ee78-d9e6-4719-8cb5-e06be3579d4b/commoncode/1.0.0/commoncode.raml
  