[{
              
              "sid": 124,
              "sname": "ram9922",
              "saddr": {
                "city": "VZG",
                "state": "AP",
                "country": "india"
              },
              "email": "niru@gmail.com"
              },{
              
              "sid": 125,
              "sname": "ram125",
              "saddr": {
                "city": "HYD",
                "state": "TS",
                "country": "india"
              },
              "email": "niru@gmail.com"
              }]