{
              
              "sid": 124,
              "sname": "ram9922",
              "saddr": {
                "city": "VZG",
                "state": "AP",
                "country": "india"
              },
              "email": "niru@gmail.com"
              }