[{
  "sid": 124,
  "sname": "ram9922",
  "city": "VZG",
  "state": "AP",
  "country": "india",
  "email": "niru@gmail.com"
},{
  "sid": 124,
  "sname": "ram9922",
  "city": "VZG",
  "state": "AP",
  "country": "india",
  "email": "niru@gmail.com"
}]